compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

# Systems for which Yarn should install packages.
# @see: https://yarnpkg.com/configuration/yarnrc#supportedArchitectures
supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - x64
    - arm64

# Do not run postinstall scripts from 3rd party packages
# @see: https://pnpm.io/supply-chain-security
# @see: https://yarnpkg.com/configuration/yarnrc#enableScripts
enableScripts: false

# reduce the likelihood of installing compromised packages
# @see: https://yarnpkg.com/configuration/yarnrc#npmMinimalAgeGate
npmMinimalAgeGate: 10080 # 7 days in minutes; 60 * 24 * 7
