name: 'setup and install'
description: 'Setup Node and Install Dependencies'
runs:
  using: 'composite'
  steps:
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'

    - name: Install dependencies
      shell: bash
      run: yarn --immutable --inline-builds
