name: 'setup and install'
description: 'Setup Node and Install Dependencies'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: ./.github/actions/setup-node

    - name: Restore Yarn Cache
      uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
      with:
        path: ./.yarn/cache
        key: ${{ runner.os }}-Yarn-main
        restore-keys: |
          ${{ runner.os }}-Yarn-main-

    - name: Restore Task Cache
      uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
      with:
        path: ./.turbo/cache
        key: ${{ runner.os }}-Task-main

    - name: Install dependencies
      uses: ./.github/actions/deps-install
