name: Pull Request Meta

on:
  pull_request:
    types: [opened]

jobs:
  process_pr_meta:
    name: Process PR meta
    runs-on: ubuntu-24.04
    steps:
      - name: Assign to author
        uses: samspills/assign-pr-to-author@223a87a821f7e7447cfb5221bc53ceeb633341c2 # v1.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Add labels
        uses: TimonVS/pr-labeler-action@f9c084306ce8b3f488a8f3ee1ccedc6da131d1af # v5.0.0
        with:
          configuration-path: .github/pr-labeler.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
